import { useState, useEffect } from 'react'
import { useForm, useFieldArray } from 'react-hook-form'
import { XMarkIcon, PlusIcon, TrashIcon } from '@heroicons/react/24/outline'
import api from '../services/api'
import toast from 'react-hot-toast'
import LoadingSpinner from './LoadingSpinner'

const AddPurchaseModal = ({ onClose, onSaved }) => {
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [invoiceNumberPreview, setInvoiceNumberPreview] = useState('')
  const [loadingPreview, setLoadingPreview] = useState(true)
  
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
    watch,
    setValue
  } = useForm({
    defaultValues: {
      invoiceNumber: '', // Will be auto-generated by backend
      supplierName: '',
      invoiceDate: new Date().toISOString().split('T')[0],
      totalAmount: 0,
      notes: '',
      items: [{ name: '', quantity: 1, purchasePrice: 0, sku: '', category: '', description: '' }]
    }
  })

  // Fetch invoice number preview when modal opens
  useEffect(() => {
    const fetchInvoiceNumberPreview = async () => {
      try {
        setLoadingPreview(true)
        // Call a backend endpoint to get invoice number preview
        // For now, we'll generate it on the backend when submitting
        // But we can show a placeholder
        setInvoiceNumberPreview('Auto-generated')
      } catch (error) {
        console.error('Failed to fetch invoice number preview:', error)
        setInvoiceNumberPreview('Auto-generated')
      } finally {
        setLoadingPreview(false)
      }
    }
    fetchInvoiceNumberPreview()
  }, [])

  const { fields, append, remove } = useFieldArray({
    control,
    name: 'items'
  })

  const watchedItems = watch('items')

  // Calculate total amount from items
  const calculateTotal = () => {
    const total = watchedItems.reduce((sum, item) => {
      const quantity = parseFloat(item?.quantity) || 0
      const price = parseFloat(item?.purchasePrice) || 0
      return sum + (quantity * price)
    }, 0)
    setValue('totalAmount', total.toFixed(2))
    return total
  }

  // Update total when items change
  useEffect(() => {
    calculateTotal()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [watchedItems])

  const addItem = () => {
    append({ name: '', quantity: 1, purchasePrice: 0, sku: '', category: '', description: '' })
  }

  const removeItem = (index) => {
    if (fields.length > 1) {
      remove(index)
      setTimeout(() => calculateTotal(), 100)
    } else {
      toast.error('At least one item is required')
    }
  }

  const onSubmit = async (data) => {
    // Validate items
    const validItems = data.items.filter(item => 
      item.name && item.name.trim() && 
      item.quantity > 0 && 
      item.purchasePrice >= 0
    )

    if (validItems.length === 0) {
      toast.error('Please add at least one valid product')
      return
    }

    setIsSubmitting(true)
    try {
      const payload = {
        // invoiceNumber is optional - backend will auto-generate if not provided
        invoiceNumber: data.invoiceNumber?.trim() || undefined,
        supplierName: data.supplierName || null,
        invoiceDate: data.invoiceDate,
        totalAmount: parseFloat(data.totalAmount) || calculateTotal(),
        notes: data.notes || null,
        products: validItems.map(item => ({
          name: item.name.trim(),
          quantity: parseInt(item.quantity),
          purchasePrice: parseFloat(item.purchasePrice),
          sku: item.sku?.trim() || null,
          category: item.category?.trim() || null,
          description: item.description?.trim() || null
        }))
      }

      await api.post('/purchase-invoice/with-products', payload)
      toast.success('Purchase invoice created successfully!')
      onSaved()
    } catch (error) {
      const errorMessage = error.response?.data?.error || error.response?.data?.message || 'Failed to create purchase invoice'
      toast.error(errorMessage)
      console.error('Create purchase invoice error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
      <div className="relative top-10 mx-auto p-5 border w-11/12 max-w-4xl shadow-lg rounded-md bg-white mb-10">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-xl font-bold text-gray-900">
            Add Purchase Invoice
          </h3>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <XMarkIcon className="h-6 w-6" />
          </button>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          {/* Invoice Details Section */}
          <div className="border-b pb-4">
            <h4 className="text-lg font-semibold text-gray-900 mb-4">Invoice Details</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Invoice Number
                </label>
                <input
                  {...register('invoiceNumber')}
                  className="input-field bg-gray-100 text-gray-600 border-2 cursor-not-allowed"
                  placeholder={loadingPreview ? 'Loading...' : 'Auto-generated (leave empty)'}
                  readOnly
                  title="Invoice number will be auto-generated by the system"
                />
                <p className="text-xs text-gray-600 mt-1">
                  Invoice number will be auto-generated in the format: <span className="font-mono">BUSINESSCODE-MONTH-YEAR-SEQUENCE</span>
                </p>
              </div>

              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Supplier Name
                </label>
                <input
                  {...register('supplierName')}
                  className="input-field bg-white text-gray-900 border-2"
                  placeholder="Enter supplier name"
                />
              </div>

              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Invoice Date *
                </label>
                <input
                  {...register('invoiceDate', { required: 'Invoice date is required' })}
                  type="date"
                  className="input-field bg-white text-gray-900 border-2"
                />
                {errors.invoiceDate && (
                  <p className="text-red-500 text-xs mt-1">{errors.invoiceDate.message}</p>
                )}
              </div>

              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Total Amount (Rs.) *
                </label>
                <input
                  {...register('totalAmount', { 
                    required: 'Total amount is required',
                    min: { value: 0, message: 'Amount must be positive' }
                  })}
                  type="number"
                  step="0.01"
                  min="0"
                  className="input-field bg-white text-gray-900 border-2"
                  placeholder="0.00"
                  readOnly
                />
                {errors.totalAmount && (
                  <p className="text-red-500 text-xs mt-1">{errors.totalAmount.message}</p>
                )}
                <p className="text-xs text-gray-600 mt-1">Auto-calculated from items</p>
              </div>
            </div>

            <div className="form-group mt-4">
              <label className="block text-sm font-bold text-gray-900 mb-2">
                Notes
              </label>
              <textarea
                {...register('notes')}
                className="input-field bg-white text-gray-900 border-2"
                rows={3}
                placeholder="Enter additional notes"
              />
            </div>
          </div>

          {/* Products Section */}
          <div>
            <div className="flex justify-between items-center mb-4">
              <h4 className="text-lg font-semibold text-gray-900">Products</h4>
              <button
                type="button"
                onClick={addItem}
                className="btn-primary flex items-center text-sm"
              >
                <PlusIcon className="h-4 w-4 mr-1" />
                Add Product
              </button>
            </div>

            <div className="space-y-4">
              {fields.map((field, index) => {
                const itemErrors = errors.items?.[index]
                const item = watchedItems[index]
                const itemTotal = (parseFloat(item?.quantity) || 0) * (parseFloat(item?.purchasePrice) || 0)

                return (
                  <div key={field.id} className="border rounded-lg p-4 bg-gray-50">
                    <div className="flex justify-between items-center mb-3">
                      <h5 className="font-semibold text-gray-900">Product {index + 1}</h5>
                      {fields.length > 1 && (
                        <button
                          type="button"
                          onClick={() => removeItem(index)}
                          className="text-red-600 hover:text-red-800"
                        >
                          <TrashIcon className="h-5 w-5" />
                        </button>
                      )}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Product Name *
                        </label>
                        <input
                          {...register(`items.${index}.name`, { 
                            required: 'Product name is required',
                            onChange: () => setTimeout(() => calculateTotal(), 100)
                          })}
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="Enter product name"
                        />
                        {itemErrors?.name && (
                          <p className="text-red-500 text-xs mt-1">{itemErrors.name.message}</p>
                        )}
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Quantity *
                        </label>
                        <input
                          {...register(`items.${index}.quantity`, { 
                            required: 'Quantity is required',
                            min: { value: 1, message: 'Quantity must be at least 1' },
                            onChange: () => setTimeout(() => calculateTotal(), 100)
                          })}
                          type="number"
                          min="1"
                          step="1"
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="1"
                        />
                        {itemErrors?.quantity && (
                          <p className="text-red-500 text-xs mt-1">{itemErrors.quantity.message}</p>
                        )}
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Purchase Price (Rs.) *
                        </label>
                        <input
                          {...register(`items.${index}.purchasePrice`, { 
                            required: 'Purchase price is required',
                            min: { value: 0, message: 'Price must be positive' },
                            onChange: () => setTimeout(() => calculateTotal(), 100)
                          })}
                          type="number"
                          step="0.01"
                          min="0"
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="0.00"
                        />
                        {itemErrors?.purchasePrice && (
                          <p className="text-red-500 text-xs mt-1">{itemErrors.purchasePrice.message}</p>
                        )}
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          SKU
                        </label>
                        <input
                          {...register(`items.${index}.sku`)}
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="Enter SKU (optional)"
                        />
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Category
                        </label>
                        <input
                          {...register(`items.${index}.category`)}
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="Enter category (optional)"
                        />
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Item Total (Rs.)
                        </label>
                        <input
                          type="text"
                          value={itemTotal.toFixed(2)}
                          className="input-field bg-gray-100 text-gray-900 border-2"
                          readOnly
                        />
                      </div>
                    </div>

                    <div className="form-group mt-4">
                      <label className="block text-sm font-bold text-gray-900 mb-2">
                        Description
                      </label>
                      <textarea
                        {...register(`items.${index}.description`)}
                        className="input-field bg-white text-gray-900 border-2"
                        rows={2}
                        placeholder="Enter product description (optional)"
                      />
                    </div>
                  </div>
                )
              })}
            </div>
          </div>

          {/* Footer Actions */}
          <div className="flex justify-end space-x-3 pt-4 border-t">
            <button
              type="button"
              onClick={onClose}
              className="btn-secondary"
              disabled={isSubmitting}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn-primary flex items-center"
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <>
                  <LoadingSpinner size="sm" className="mr-2" />
                  Creating...
                </>
              ) : (
                'Create Purchase Invoice'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

export default AddPurchaseModal

