import { useState, useEffect } from 'react'
import { useForm, useFieldArray } from 'react-hook-form'
import { XMarkIcon, PlusIcon, TrashIcon } from '@heroicons/react/24/outline'
import api from '../services/api'
import toast from 'react-hot-toast'
import LoadingSpinner from './LoadingSpinner'
import { useTenant } from '../hooks'

const AddPurchaseModal = ({ onClose, onSaved }) => {
  const { tenant } = useTenant()
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [invoiceNumberPreview, setInvoiceNumberPreview] = useState('')
  const [loadingPreview, setLoadingPreview] = useState(true)
  const [categories, setCategories] = useState([])
  const [loadingCategories, setLoadingCategories] = useState(false)
  const [newCategoryInputs, setNewCategoryInputs] = useState({}) // Track which items have new category input
  
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
    watch,
    setValue
  } = useForm({
    defaultValues: {
      invoiceNumber: '', // Will be auto-generated by backend
      supplierName: '',
      invoiceDate: new Date().toISOString().split('T')[0],
      totalAmount: 0,
      paymentStatus: '',
      paymentAmount: '',
      paymentMethod: 'Cash',
      notes: '',
      items: [{ name: '', quantity: 1, purchasePrice: 0, sku: '', category: '', description: '' }]
    }
  })

  // Fetch invoice number preview when modal opens
  useEffect(() => {
    const fetchInvoiceNumberPreview = async () => {
      try {
        setLoadingPreview(true)
        // Call a backend endpoint to get invoice number preview
        // For now, we'll generate it on the backend when submitting
        // But we can show a placeholder
        setInvoiceNumberPreview('Auto-generated')
      } catch (error) {
        console.error('Failed to fetch invoice number preview:', error)
        setInvoiceNumberPreview('Auto-generated')
      } finally {
        setLoadingPreview(false)
      }
    }
    fetchInvoiceNumberPreview()
  }, [])

  // Fetch existing categories from products
  useEffect(() => {
    const fetchCategories = async () => {
      if (!tenant?.id) return
      
      try {
        setLoadingCategories(true)
        const response = await api.get(`/products/tenant/${tenant.id}`)
        const products = response.data.products || []
        const uniqueCategories = [...new Set(products.map(p => p.category).filter(Boolean))]
        setCategories(uniqueCategories.sort())
      } catch (error) {
        console.error('Failed to fetch categories:', error)
      } finally {
        setLoadingCategories(false)
      }
    }

    fetchCategories()
  }, [tenant])

  const { fields, append, remove } = useFieldArray({
    control,
    name: 'items'
  })

  const watchedItems = watch('items')

  // Calculate total amount from items
  const calculateTotal = () => {
    const total = watchedItems.reduce((sum, item) => {
      const quantity = parseFloat(item?.quantity) || 0
      const price = parseFloat(item?.purchasePrice) || 0
      return sum + (quantity * price)
    }, 0)
    setValue('totalAmount', total.toFixed(2))
    return total
  }

  // Update total when items change
  useEffect(() => {
    calculateTotal()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [watchedItems])

  const addItem = () => {
    append({ name: '', quantity: 1, purchasePrice: 0, sku: '', category: '', description: '' })
  }

  const removeItem = (index) => {
    if (fields.length > 1) {
      remove(index)
      setTimeout(() => calculateTotal(), 100)
    } else {
      toast.error('At least one item is required')
    }
  }

  const onSubmit = async (data) => {
    // Validate items
    const validItems = data.items.filter(item => 
      item.name && item.name.trim() && 
      item.quantity > 0 && 
      item.purchasePrice >= 0
    )

    if (validItems.length === 0) {
      toast.error('Please add at least one valid product')
      return
    }

    setIsSubmitting(true)
    try {
      const totalAmount = parseFloat(data.totalAmount) || calculateTotal()
      
      // Determine payment amount based on payment status
      let paymentAmount = 0
      if (data.paymentStatus === 'paid') {
        paymentAmount = totalAmount
      } else if (data.paymentStatus === 'partial') {
        paymentAmount = data.paymentAmount ? parseFloat(data.paymentAmount) : 0
      } else {
        paymentAmount = 0 // unpaid
      }
      
      if (paymentAmount < 0 || paymentAmount > totalAmount) {
        toast.error('Payment amount must be between 0 and total amount')
        setIsSubmitting(false)
        return
      }

      if (data.paymentStatus === 'paid' && paymentAmount !== totalAmount) {
        toast.error('Payment amount must equal total amount for fully paid invoices')
        setIsSubmitting(false)
        return
      }

      if (data.paymentStatus === 'partial' && (paymentAmount <= 0 || paymentAmount >= totalAmount)) {
        toast.error('Payment amount must be greater than 0 and less than total amount for partial payment')
        setIsSubmitting(false)
        return
      }

      const payload = {
        // invoiceNumber is optional - backend will auto-generate if not provided
        invoiceNumber: data.invoiceNumber?.trim() || undefined,
        supplierName: data.supplierName || null,
        invoiceDate: data.invoiceDate,
        totalAmount: totalAmount,
        paymentAmount: paymentAmount > 0 ? paymentAmount : undefined,
        paymentMethod: paymentAmount > 0 ? (data.paymentMethod || 'Cash') : undefined,
        notes: data.notes || null,
        products: validItems.map(item => {
          // Use newCategory if it exists, otherwise use category
          const categoryValue = item.newCategory?.trim() 
            ? item.newCategory.trim() 
            : (item.category?.trim() || null)
          
          return {
            name: item.name.trim(),
            quantity: parseInt(item.quantity),
            purchasePrice: parseFloat(item.purchasePrice),
            sku: item.sku?.trim() || null,
            category: categoryValue,
            description: item.description?.trim() || null
          }
        })
      }

      await api.post('/purchase-invoice/with-products', payload)
      toast.success('Purchase invoice created successfully!')
      onSaved()
    } catch (error) {
      const errorMessage = error.response?.data?.error || error.response?.data?.message || 'Failed to create purchase invoice'
      toast.error(errorMessage)
      console.error('Create purchase invoice error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
      <div className="relative top-10 mx-auto p-5 border w-11/12 max-w-4xl shadow-lg rounded-md bg-white mb-10">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-xl font-bold text-gray-900">
            Add Purchase Invoice
          </h3>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <XMarkIcon className="h-6 w-6" />
          </button>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          {/* Invoice Details Section */}
          <div className="border-b pb-4">
            <h4 className="text-lg font-semibold text-gray-900 mb-4">Invoice Details</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Invoice Number
                </label>
                <input
                  {...register('invoiceNumber')}
                  className="input-field bg-gray-100 text-gray-600 border-2 cursor-not-allowed"
                  placeholder={loadingPreview ? 'Loading...' : 'Auto-generated (leave empty)'}
                  readOnly
                  title="Invoice number will be auto-generated by the system"
                />
                <p className="text-xs text-gray-600 mt-1">
                  Invoice number will be auto-generated in the format: <span className="font-mono">BUSINESSCODE-MONTH-YEAR-SEQUENCE</span>
                </p>
              </div>

              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Supplier Name
                </label>
                <input
                  {...register('supplierName')}
                  className="input-field bg-white text-gray-900 border-2"
                  placeholder="Enter supplier name"
                />
              </div>

              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Invoice Date *
                </label>
                <input
                  {...register('invoiceDate', { required: 'Invoice date is required' })}
                  type="date"
                  className="input-field bg-white text-gray-900 border-2"
                />
                {errors.invoiceDate && (
                  <p className="text-red-500 text-xs mt-1">{errors.invoiceDate.message}</p>
                )}
              </div>

              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Total Amount (Rs.) *
                </label>
                <input
                  {...register('totalAmount', { 
                    required: 'Total amount is required',
                    min: { value: 0, message: 'Amount must be positive' }
                  })}
                  type="number"
                  step="0.01"
                  min="0"
                  className="input-field bg-white text-gray-900 border-2"
                  placeholder="0.00"
                  readOnly
                />
                {errors.totalAmount && (
                  <p className="text-red-500 text-xs mt-1">{errors.totalAmount.message}</p>
                )}
                <p className="text-xs text-gray-600 mt-1">Auto-calculated from items</p>
              </div>

              <div className="form-group">
                <label className="block text-sm font-bold text-gray-900 mb-2">
                  Payment Status <span className="text-red-500">*</span>
                </label>
                <select
                  {...register('paymentStatus', { required: 'Please select payment status' })}
                  className="input-field bg-white text-gray-900 border-2"
                  onChange={(e) => {
                    register('paymentStatus').onChange(e)
                    if (e.target.value === 'unpaid') {
                      setValue('paymentAmount', '')
                      setValue('paymentMethod', 'Cash')
                    } else if (e.target.value === 'paid') {
                      const total = parseFloat(watch('totalAmount')) || 0
                      setValue('paymentAmount', total.toFixed(2))
                    } else if (e.target.value === 'partial') {
                      setValue('paymentAmount', '')
                    }
                  }}
                >
                  <option value="">Select payment status</option>
                  <option value="unpaid">Unpaid (Cash on Delivery)</option>
                  <option value="partial">Partially Paid</option>
                  <option value="paid">Fully Paid</option>
                </select>
                {errors.paymentStatus && (
                  <p className="text-red-500 text-xs mt-1">{errors.paymentStatus.message}</p>
                )}
              </div>

              {watch('paymentStatus') && watch('paymentStatus') !== 'unpaid' && (
                <>
                  <div className="form-group">
                    <label className="block text-sm font-bold text-gray-900 mb-2">
                      Payment Amount (Rs.) <span className="text-red-500">*</span>
                    </label>
                    <input
                      {...register('paymentAmount', {
                        required: watch('paymentStatus') !== 'unpaid' ? 'Payment amount is required' : false,
                        min: { value: 0, message: 'Payment amount must be positive' },
                        validate: (value) => {
                          const total = parseFloat(watch('totalAmount')) || 0
                          const payment = parseFloat(value) || 0
                          if (payment > total) {
                            return 'Payment amount cannot exceed total amount'
                          }
                          if (watch('paymentStatus') === 'paid' && payment < total) {
                            return 'Payment amount must equal total amount for fully paid'
                          }
                          if (watch('paymentStatus') === 'partial' && payment >= total) {
                            return 'Payment amount must be less than total amount for partial payment'
                          }
                          if (watch('paymentStatus') !== 'unpaid' && payment <= 0) {
                            return 'Payment amount must be greater than 0'
                          }
                          return true
                        }
                      })}
                      type="number"
                      step="0.01"
                      min="0"
                      className="input-field bg-white text-gray-900 border-2"
                      placeholder="0.00"
                      disabled={watch('paymentStatus') === 'paid'}
                    />
                    {errors.paymentAmount && (
                      <p className="text-red-500 text-xs mt-1">{errors.paymentAmount.message}</p>
                    )}
                    {watch('paymentStatus') === 'paid' && (
                      <p className="text-xs text-green-600 mt-1">
                        Full amount ({watch('totalAmount') || '0.00'} Rs.) will be used
                      </p>
                    )}
                    {watch('paymentStatus') === 'partial' && (
                      <p className="text-xs text-gray-600 mt-1">
                        Remaining amount will be recorded as payable
                      </p>
                    )}
                  </div>

                  <div className="form-group">
                    <label className="block text-sm font-bold text-gray-900 mb-2">
                      Payment Method <span className="text-red-500">*</span>
                    </label>
                    <select
                      {...register('paymentMethod', {
                        required: watch('paymentStatus') !== 'unpaid' ? 'Payment method is required' : false
                      })}
                      className="input-field bg-white text-gray-900 border-2"
                    >
                      <option value="">Select payment method</option>
                      <option value="Cash">Cash</option>
                      <option value="Bank Transfer">Bank Transfer</option>
                      <option value="Cheque">Cheque</option>
                      <option value="Credit Card">Credit Card</option>
                      <option value="Other">Other</option>
                    </select>
                    {errors.paymentMethod && (
                      <p className="text-red-500 text-xs mt-1">{errors.paymentMethod.message}</p>
                    )}
                  </div>
                </>
              )}
            </div>

            <div className="form-group mt-4">
              <label className="block text-sm font-bold text-gray-900 mb-2">
                Notes
              </label>
              <textarea
                {...register('notes')}
                className="input-field bg-white text-gray-900 border-2"
                rows={3}
                placeholder="Enter additional notes"
              />
            </div>
          </div>

          {/* Products Section */}
          <div>
            <div className="flex justify-between items-center mb-4">
              <h4 className="text-lg font-semibold text-gray-900">Products</h4>
              <button
                type="button"
                onClick={addItem}
                className="btn-primary flex items-center text-sm"
              >
                <PlusIcon className="h-4 w-4 mr-1" />
                Add Product
              </button>
            </div>

            <div className="space-y-4">
              {fields.map((field, index) => {
                const itemErrors = errors.items?.[index]
                const item = watchedItems[index]
                const itemTotal = (parseFloat(item?.quantity) || 0) * (parseFloat(item?.purchasePrice) || 0)

                return (
                  <div key={field.id} className="border rounded-lg p-4 bg-gray-50">
                    <div className="flex justify-between items-center mb-3">
                      <h5 className="font-semibold text-gray-900">Product {index + 1}</h5>
                      {fields.length > 1 && (
                        <button
                          type="button"
                          onClick={() => removeItem(index)}
                          className="text-red-600 hover:text-red-800"
                        >
                          <TrashIcon className="h-5 w-5" />
                        </button>
                      )}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Product Name *
                        </label>
                        <input
                          {...register(`items.${index}.name`, { 
                            required: 'Product name is required',
                            onChange: () => setTimeout(() => calculateTotal(), 100)
                          })}
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="Enter product name"
                        />
                        {itemErrors?.name && (
                          <p className="text-red-500 text-xs mt-1">{itemErrors.name.message}</p>
                        )}
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Quantity *
                        </label>
                        <input
                          {...register(`items.${index}.quantity`, { 
                            required: 'Quantity is required',
                            min: { value: 1, message: 'Quantity must be at least 1' },
                            onChange: () => setTimeout(() => calculateTotal(), 100)
                          })}
                          type="number"
                          min="1"
                          step="1"
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="1"
                        />
                        {itemErrors?.quantity && (
                          <p className="text-red-500 text-xs mt-1">{itemErrors.quantity.message}</p>
                        )}
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Purchase Price (Rs.) *
                        </label>
                        <input
                          {...register(`items.${index}.purchasePrice`, { 
                            required: 'Purchase price is required',
                            min: { value: 0, message: 'Price must be positive' },
                            onChange: () => setTimeout(() => calculateTotal(), 100)
                          })}
                          type="number"
                          step="0.01"
                          min="0"
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="0.00"
                        />
                        {itemErrors?.purchasePrice && (
                          <p className="text-red-500 text-xs mt-1">{itemErrors.purchasePrice.message}</p>
                        )}
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          SKU
                        </label>
                        <input
                          {...register(`items.${index}.sku`)}
                          className="input-field bg-white text-gray-900 border-2"
                          placeholder="Enter SKU (optional)"
                        />
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Category
                        </label>
                        {loadingCategories ? (
                          <div className="w-full px-3 py-2 bg-gray-50 text-gray-500 border-2 border-gray-300 rounded-lg flex items-center">
                            <LoadingSpinner size="sm" />
                            <span className="ml-2 text-xs">Loading...</span>
                          </div>
                        ) : (
                          <>
                            <select
                              {...register(`items.${index}.category`)}
                              style={{ color: '#111827', backgroundColor: '#ffffff' }}
                              onChange={(e) => {
                                const value = e.target.value
                                register(`items.${index}.category`).onChange(e)
                                if (value === '__new__') {
                                  setNewCategoryInputs(prev => ({ ...prev, [index]: true }))
                                  setValue(`items.${index}.category`, '')
                                } else {
                                  setNewCategoryInputs(prev => {
                                    const updated = { ...prev }
                                    delete updated[index]
                                    return updated
                                  })
                                  setValue(`items.${index}.newCategory`, '')
                                }
                              }}
                              className="input-field bg-white text-gray-900 border-2"
                            >
                              <option value="" style={{ color: '#111827', backgroundColor: '#ffffff' }}>Select a category (optional)</option>
                              {categories.map(category => (
                                <option key={category} value={category} style={{ color: '#111827', backgroundColor: '#ffffff' }}>
                                  {category}
                                </option>
                              ))}
                              <option value="__new__" style={{ color: '#111827', backgroundColor: '#ffffff' }}>+ Add New Category</option>
                            </select>
                            {newCategoryInputs[index] && (
                              <input
                                {...register(`items.${index}.newCategory`)}
                                className="input-field bg-white text-gray-900 border-2 mt-2"
                                placeholder="Enter new category name"
                                autoFocus
                              />
                            )}
                          </>
                        )}
                      </div>

                      <div className="form-group">
                        <label className="block text-sm font-bold text-gray-900 mb-2">
                          Item Total (Rs.)
                        </label>
                        <input
                          type="text"
                          value={itemTotal.toFixed(2)}
                          className="input-field bg-gray-100 text-gray-900 border-2"
                          readOnly
                        />
                      </div>
                    </div>

                    <div className="form-group mt-4">
                      <label className="block text-sm font-bold text-gray-900 mb-2">
                        Description
                      </label>
                      <textarea
                        {...register(`items.${index}.description`)}
                        className="input-field bg-white text-gray-900 border-2"
                        rows={2}
                        placeholder="Enter product description (optional)"
                      />
                    </div>
                  </div>
                )
              })}
            </div>
          </div>

          {/* Footer Actions */}
          <div className="flex justify-end space-x-3 pt-4 border-t">
            <button
              type="button"
              onClick={onClose}
              className="btn-secondary"
              disabled={isSubmitting}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn-primary flex items-center"
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <>
                  <LoadingSpinner size="sm" className="mr-2" />
                  Creating...
                </>
              ) : (
                'Create Purchase Invoice'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

export default AddPurchaseModal

