import { lazy } from 'react'

// Lazy load heavy components
export const LazyEnhancedProductsDashboard = lazy(() => import('../pages/EnhancedProductsDashboard'))
export const LazyAdminDashboard = lazy(() => import('../pages/AdminDashboard'))
export const LazyBusinessDashboard = lazy(() => import('../pages/BusinessDashboard'))
export const LazyBusinessDashboardRefactored = lazy(() => import('../pages/BusinessDashboardRefactored'))
export const LazyModernDashboard = lazy(() => import('../pages/ModernDashboardPage'))
export const LazyOrdersScreen = lazy(() => import('../pages/OrdersScreen'))
export const LazyOrdersPage = lazy(() => import('../pages/OrdersPage'))
export const LazyFormsPage = lazy(() => import('../pages/FormsPage'))
export const LazyCustomersPage = lazy(() => import('../pages/CustomersPage'))
export const LazyProductsPage = lazy(() => import('../pages/ProductsPage'))
export const LazyPurchasesPage = lazy(() => import('../pages/PurchasesPage'))
export const LazyReturnsPage = lazy(() => import('../pages/ReturnsPage'))
export const LazyVendorsPage = lazy(() => import('../pages/VendorsPage'))
export const LazyOrderDetailsPage = lazy(() => import('../pages/OrderDetailsPage'))
export const LazyStockKeeperDashboard = lazy(() => import('../pages/StockKeeperDashboard'))
export const LazyTenantDetails = lazy(() => import('../pages/TenantDetails'))

// Lazy load modals
export const LazyOrderDetailsModal = lazy(() => import('./OrderDetailsModal'))
export const LazyProductManagementModal = lazy(() => import('./ProductManagementModal'))
export const LazyCustomerDetailsModal = lazy(() => import('./CustomerDetailsModal'))
export const LazyAddCustomerModal = lazy(() => import('./AddCustomerModal'))
export const LazyCustomerDetailsPage = lazy(() => import('../pages/CustomerDetailsPage'))
export const LazyAddCustomerPage = lazy(() => import('../pages/AddCustomerPage'))
export const LazyAddProductPage = lazy(() => import('../pages/AddProductPage'))
export const LazyEditProductPage = lazy(() => import('../pages/EditProductPage'))
export const LazyProductManagementPage = lazy(() => import('../pages/ProductManagementPage'))
export const LazyReportsPage = lazy(() => import('../pages/ReportsPage'))
export const LazyEditPurchasePage = lazy(() => import('../pages/EditPurchasePage'))
export const LazyCreateFormPage = lazy(() => import('../pages/CreateFormPage'))
export const LazyEditFormPage = lazy(() => import('../pages/EditFormPage'))
export const LazySettingsPage = lazy(() => import('../pages/SettingsPage'))
export const LazyEnhancedProductModal = lazy(() => import('./EnhancedProductModal'))
export const LazyInvoiceUploadModal = lazy(() => import('./InvoiceUploadModal'))
export const LazyProductHistoryModal = lazy(() => import('./ProductHistoryModal'))
export const LazyProductImageUpload = lazy(() => import('./ProductImageUpload'))
export const LazyPurchaseInvoiceModal = lazy(() => import('./PurchaseInvoiceModal'))
export const LazyReturnsManagement = lazy(() => import('./ReturnsManagement'))

// Lazy load forms
export const LazyClientFormDynamic = lazy(() => import('../pages/ClientFormDynamic'))
export const LazyOrderReceipt = lazy(() => import('../pages/OrderReceipt'))
